name = "mpsl"
version = "0.1.0"
defaultTargets = ["MPSL", "MPSLElabTests", "MPSLSemanticsTests", "MPSLPrettyPrintTests"]

[[lean_lib]]
name = "MPSL"

[[lean_lib]]
name = "MPSLTest"

[[lean_lib]]
name = "MPSLElabTests"

[[lean_lib]]
name = "MPSLSemanticsTests"

[[lean_lib]]
name = "MPSLPrettyPrintTests"
