import MPSL.Syntax.Denote

set_option autoImplicit false

namespace MPSL.ProofMode

universe u v w

/-- Additive and multiplicative composition of proof-mode hypotheses. -/
inductive Bunch (Loc : Type u) (Val : Type v) : Type (max u v) where
  | empty
  | hyp (name : String) (assertion : IProp Loc Val)
  | additive (left right : Bunch Loc Val)
  | multiplicative (left right : Bunch Loc Val)

namespace Bunch

variable {Loc : Type u} {Val : Type v}

def denote : Bunch Loc Val -> IProp Loc Val
  | .empty => IProp.truth
  | .hyp _ assertion => assertion
  | .additive left right => IProp.and left.denote right.denote
  | .multiplicative left right => IProp.sep left.denote right.denote

def lookup (name : String) : Bunch Loc Val -> Option (IProp Loc Val)
  | .empty => none
  | .hyp candidate assertion => if candidate = name then some assertion else none
  | .additive left right
  | .multiplicative left right =>
      match left.lookup name with
      | some assertion => some assertion
      | none => right.lookup name

/-- Replace the first named hypothesis and return its previous assertion. -/
def replace (name : String) (replacement : Bunch Loc Val) :
    Bunch Loc Val -> Option (IProp Loc Val × Bunch Loc Val)
  | .empty => none
  | .hyp candidate assertion =>
      if candidate = name then some (assertion, replacement) else none
  | .additive left right =>
      match replace name replacement left with
      | some (assertion, updated) => some (assertion, .additive updated right)
      | none =>
          match replace name replacement right with
          | some (assertion, updated) => some (assertion, .additive left updated)
          | none => none
  | .multiplicative left right =>
      match replace name replacement left with
      | some (assertion, updated) => some (assertion, .multiplicative updated right)
      | none =>
          match replace name replacement right with
          | some (assertion, updated) => some (assertion, .multiplicative left updated)
          | none => none

/-- Extract a hypothesis reachable only through multiplicative nodes. -/
def extract (name : String) : Bunch Loc Val -> Option (IProp Loc Val × Bunch Loc Val)
  | .empty => none
  | .hyp candidate assertion =>
      if candidate = name then some (assertion, .empty) else none
  | .additive _ _ => none
  | .multiplicative left right =>
      match extract name left with
      | some (assertion, updated) => some (assertion, .multiplicative updated right)
      | none =>
          match extract name right with
          | some (assertion, updated) => some (assertion, .multiplicative left updated)
          | none => none

/-- Extract a nonempty ordered list of hypotheses through multiplicative nodes. -/
def extractMany : List String -> Bunch Loc Val -> Option (IProp Loc Val × Bunch Loc Val)
  | [], _ => none
  | [name], context => extract name context
  | name :: next :: rest, context => do
      let (assertion, afterFirst) ← extract name context
      let (remainingAssertions, remaining) ← extractMany (next :: rest) afterFirst
      pure (IProp.sep assertion remainingAssertions, remaining)

def names : Bunch Loc Val -> List String
  | .empty => []
  | .hyp name _ => [name]
  | .additive left right
  | .multiplicative left right => left.names ++ right.names

def contains (name : String) (context : Bunch Loc Val) : Bool :=
  context.names.contains name

/-- Algebraic equivalence generated by the additive and multiplicative BI laws. -/
inductive Structural : Bunch Loc Val -> Bunch Loc Val -> Prop where
  | refl (context : Bunch Loc Val) : Structural context context
  | symm {left right : Bunch Loc Val} : Structural left right -> Structural right left
  | trans {left middle right : Bunch Loc Val} :
      Structural left middle -> Structural middle right -> Structural left right
  | additiveCongr {left₁ left₂ right₁ right₂ : Bunch Loc Val} :
      Structural left₁ left₂ -> Structural right₁ right₂ ->
      Structural (.additive left₁ right₁) (.additive left₂ right₂)
  | multiplicativeCongr {left₁ left₂ right₁ right₂ : Bunch Loc Val} :
      Structural left₁ left₂ -> Structural right₁ right₂ ->
      Structural (.multiplicative left₁ right₁) (.multiplicative left₂ right₂)
  | additiveComm (left right : Bunch Loc Val) :
      Structural (.additive left right) (.additive right left)
  | additiveAssoc (first second third : Bunch Loc Val) :
      Structural (.additive (.additive first second) third)
        (.additive first (.additive second third))
  | additiveUnitLeft (context : Bunch Loc Val) :
      Structural (.additive .empty context) context
  | additiveUnitRight (context : Bunch Loc Val) :
      Structural (.additive context .empty) context
  | additiveContract (context : Bunch Loc Val) :
      Structural (.additive context context) context
  | multiplicativeComm (left right : Bunch Loc Val) :
      Structural (.multiplicative left right) (.multiplicative right left)
  | multiplicativeAssoc (first second third : Bunch Loc Val) :
      Structural (.multiplicative (.multiplicative first second) third)
        (.multiplicative first (.multiplicative second third))
  | multiplicativeUnitLeft (context : Bunch Loc Val) :
      Structural (.multiplicative .empty context) context
  | multiplicativeUnitRight (context : Bunch Loc Val) :
      Structural (.multiplicative context .empty) context

/-- Affine deletion closed under both bunch constructors. -/
inductive Weakening : Bunch Loc Val -> Bunch Loc Val -> Prop where
  | refl (context : Bunch Loc Val) : Weakening context context
  | discard (context : Bunch Loc Val) : Weakening context .empty
  | additive {left₁ left₂ right₁ right₂ : Bunch Loc Val} :
      Weakening left₁ left₂ -> Weakening right₁ right₂ ->
      Weakening (.additive left₁ right₁) (.additive left₂ right₂)
  | multiplicative {left₁ left₂ right₁ right₂ : Bunch Loc Val} :
      Weakening left₁ left₂ -> Weakening right₁ right₂ ->
      Weakening (.multiplicative left₁ right₁) (.multiplicative left₂ right₂)

/-- Evidence that every hypothesis in a bunch is guarded by `always`. -/
inductive Boxed : Bunch Loc Val -> Prop where
  | empty : Boxed .empty
  | hyp (name : String) (proposition : IProp Loc Val) :
      Boxed (.hyp name (IProp.always proposition))
  | additive {left right : Bunch Loc Val} :
      Boxed left -> Boxed right -> Boxed (.additive left right)
  | multiplicative {left right : Bunch Loc Val} :
      Boxed left -> Boxed right -> Boxed (.multiplicative left right)

/-- A bunch with one distinguished hole. -/
inductive Hole (Loc : Type u) (Val : Type v) : Type (max u v) where
  | here
  | additiveLeft (inside : Hole Loc Val) (right : Bunch Loc Val)
  | additiveRight (left : Bunch Loc Val) (inside : Hole Loc Val)
  | multiplicativeLeft (inside : Hole Loc Val) (right : Bunch Loc Val)
  | multiplicativeRight (left : Bunch Loc Val) (inside : Hole Loc Val)

namespace Hole

def fill : Hole Loc Val -> Bunch Loc Val -> Bunch Loc Val
  | .here, replacement => replacement
  | .additiveLeft inside right, replacement => .additive (inside.fill replacement) right
  | .additiveRight left inside, replacement => .additive left (inside.fill replacement)
  | .multiplicativeLeft inside right, replacement =>
      .multiplicative (inside.fill replacement) right
  | .multiplicativeRight left inside, replacement =>
      .multiplicative left (inside.fill replacement)

end Hole

/-- Find the first named hypothesis together with its surrounding bunch. -/
def focus (name : String) : Bunch Loc Val -> Option (IProp Loc Val × Hole Loc Val)
  | .empty => none
  | .hyp candidate assertion =>
      if candidate = name then some (assertion, .here) else none
  | .additive left right =>
      match focus name left with
      | some (assertion, hole) => some (assertion, .additiveLeft hole right)
      | none =>
          match focus name right with
          | some (assertion, hole) => some (assertion, .additiveRight left hole)
          | none => none
  | .multiplicative left right =>
      match focus name left with
      | some (assertion, hole) => some (assertion, .multiplicativeLeft hole right)
      | none =>
          match focus name right with
          | some (assertion, hole) => some (assertion, .multiplicativeRight left hole)
          | none => none

/-- Extract one named multiplicative subtree while retaining its name. -/
def select (name : String) (context : Bunch Loc Val) :
    Option (Bunch Loc Val × Bunch Loc Val) := do
  let (assertion, remaining) ← extract name context
  pure (.hyp name assertion, remaining)

/-- Split out a nonempty ordered selection of multiplicative subtrees. -/
def partition : List String -> Bunch Loc Val -> Option (Bunch Loc Val × Bunch Loc Val)
  | [], _ => none
  | [name], context => select name context
  | name :: next :: rest, context => do
      let (selected, afterFirst) ← select name context
      let (remainingSelected, remaining) ← partition (next :: rest) afterFirst
      pure (.multiplicative selected remainingSelected, remaining)

theorem lookup_sound {context : Bunch Loc Val}
    {name : String} {goal : IProp Loc Val} :
    context.lookup name = some goal -> IProp.Entails context.denote goal := by
  intro found
  induction context generalizing goal with
  | empty => simp [lookup] at found
  | hyp candidate assertion =>
      by_cases same : candidate = name
      · simp [lookup, same] at found
        subst goal
        exact IProp.entails_refl assertion
      · simp [lookup, same] at found
  | additive left right leftIH rightIH =>
      cases leftFound : left.lookup name with
      | some leftGoal =>
          have sameGoal : leftGoal = goal := by
            simpa [lookup, leftFound] using found
          subst goal
          exact IProp.entails_trans
            (IProp.and_elim_left left.denote right.denote)
            (leftIH leftFound)
      | none =>
          have rightFound : right.lookup name = some goal := by
            simpa [lookup, leftFound] using found
          exact IProp.entails_trans
            (IProp.and_elim_right left.denote right.denote)
            (rightIH rightFound)
  | multiplicative left right leftIH rightIH =>
      cases leftFound : left.lookup name with
      | some leftGoal =>
          have sameGoal : leftGoal = goal := by
            simpa [lookup, leftFound] using found
          subst goal
          exact IProp.entails_trans
            (IProp.sep_elim_left left.denote right.denote)
            (leftIH leftFound)
      | none =>
          have rightFound : right.lookup name = some goal := by
            simpa [lookup, leftFound] using found
          exact IProp.entails_trans
            (IProp.sep_elim_right left.denote right.denote)
            (rightIH rightFound)

theorem replace_sound {context replacement updated : Bunch Loc Val}
    {name : String} {source : IProp Loc Val} :
    replace name replacement context = some (source, updated) ->
    IProp.Entails source replacement.denote ->
    IProp.Entails context.denote updated.denote := by
  intro replaced sourceRule
  induction context generalizing source updated with
  | empty => simp [replace] at replaced
  | hyp candidate assertion =>
      by_cases same : candidate = name
      · simp [replace, same] at replaced
        obtain ⟨rfl, rfl⟩ := replaced
        exact sourceRule
      · simp [replace, same] at replaced
  | additive left right leftIH rightIH =>
      cases leftReplaced : replace name replacement left with
      | some result =>
          obtain ⟨leftSource, leftUpdated⟩ := result
          have resultEqual : (leftSource, .additive leftUpdated right) = (source, updated) := by
            simpa [replace, leftReplaced] using replaced
          cases resultEqual
          exact IProp.and_mono (leftIH leftReplaced sourceRule)
            (IProp.entails_refl right.denote)
      | none =>
          cases rightReplaced : replace name replacement right with
          | none => simp [replace, leftReplaced, rightReplaced] at replaced
          | some result =>
              obtain ⟨rightSource, rightUpdated⟩ := result
              have resultEqual : (rightSource, .additive left rightUpdated) = (source, updated) := by
                simpa [replace, leftReplaced, rightReplaced] using replaced
              cases resultEqual
              exact IProp.and_mono (IProp.entails_refl left.denote)
                (rightIH rightReplaced sourceRule)
  | multiplicative left right leftIH rightIH =>
      cases leftReplaced : replace name replacement left with
      | some result =>
          obtain ⟨leftSource, leftUpdated⟩ := result
          have resultEqual : (leftSource, .multiplicative leftUpdated right) = (source, updated) := by
            simpa [replace, leftReplaced] using replaced
          cases resultEqual
          exact IProp.sep_mono (leftIH leftReplaced sourceRule)
            (IProp.entails_refl right.denote)
      | none =>
          cases rightReplaced : replace name replacement right with
          | none => simp [replace, leftReplaced, rightReplaced] at replaced
          | some result =>
              obtain ⟨rightSource, rightUpdated⟩ := result
              have resultEqual : (rightSource, .multiplicative left rightUpdated) = (source, updated) := by
                simpa [replace, leftReplaced, rightReplaced] using replaced
              cases resultEqual
              exact IProp.sep_mono (IProp.entails_refl left.denote)
                (rightIH rightReplaced sourceRule)

theorem extract_sound {context remaining : Bunch Loc Val}
    {name : String} {frame : IProp Loc Val} :
    extract name context = some (frame, remaining) ->
    IProp.Entails context.denote (IProp.sep frame remaining.denote) := by
  intro extracted
  induction context generalizing frame remaining with
  | empty => simp [extract] at extracted
  | hyp candidate assertion =>
      by_cases same : candidate = name
      · simp [extract, same] at extracted
        obtain ⟨rfl, rfl⟩ := extracted
        exact IProp.sep_truth_intro_right assertion
      · simp [extract, same] at extracted
  | additive left right leftIH rightIH => simp [extract] at extracted
  | multiplicative left right leftIH rightIH =>
      cases leftExtracted : extract name left with
      | some result =>
          obtain ⟨leftFrame, leftRemaining⟩ := result
          have resultEqual :
              (leftFrame, .multiplicative leftRemaining right) = (frame, remaining) := by
            simpa [extract, leftExtracted] using extracted
          cases resultEqual
          exact IProp.entails_trans
            (IProp.sep_mono (leftIH leftExtracted) (IProp.entails_refl right.denote))
            (IProp.sep_assoc_left frame leftRemaining.denote right.denote)
      | none =>
          cases rightExtracted : extract name right with
          | none => simp [extract, leftExtracted, rightExtracted] at extracted
          | some result =>
              obtain ⟨rightFrame, rightRemaining⟩ := result
              have resultEqual :
                  (rightFrame, .multiplicative left rightRemaining) = (frame, remaining) := by
                simpa [extract, leftExtracted, rightExtracted] using extracted
              cases resultEqual
              apply IProp.entails_trans
                (IProp.sep_mono (IProp.entails_refl left.denote) (rightIH rightExtracted))
              apply IProp.entails_trans
                (IProp.sep_assoc_right left.denote frame rightRemaining.denote)
              apply IProp.entails_trans
                (IProp.sep_mono (IProp.sep_comm left.denote frame)
                  (IProp.entails_refl rightRemaining.denote))
              exact IProp.sep_assoc_left frame left.denote rightRemaining.denote

theorem extractMany_sound {names : List String} {context remaining : Bunch Loc Val}
    {frame : IProp Loc Val} :
    extractMany names context = some (frame, remaining) ->
    IProp.Entails context.denote (IProp.sep frame remaining.denote) := by
  induction names generalizing context frame remaining with
  | nil => simp [extractMany]
  | cons name names induction =>
      cases names with
      | nil =>
          simpa [extractMany] using
            (extract_sound (context := context) (remaining := remaining)
              (name := name) (frame := frame))
      | cons next rest =>
          intro extracted
          simp only [extractMany] at extracted
          cases firstExtracted : extract name context with
          | none => simp [firstExtracted] at extracted
          | some firstResult =>
              obtain ⟨assertion, afterFirst⟩ := firstResult
              cases restExtracted : extractMany (next :: rest) afterFirst with
              | none => simp [firstExtracted, restExtracted] at extracted
              | some restResult =>
                  obtain ⟨remainingAssertions, finalContext⟩ := restResult
                  simp [firstExtracted, restExtracted] at extracted
                  obtain ⟨rfl, rfl⟩ := extracted
                  apply IProp.entails_trans (extract_sound firstExtracted)
                  apply IProp.entails_trans
                    (IProp.sep_mono (IProp.entails_refl assertion)
                      (induction restExtracted))
                  exact IProp.sep_assoc_right assertion remainingAssertions finalContext.denote

def SemanticallyEquivalent (left right : Bunch Loc Val) : Prop :=
  IProp.Entails left.denote right.denote ∧ IProp.Entails right.denote left.denote

/-- Every generated structural equation is a semantic equivalence:
`Γ ≡ Δ` implies both `⟦Γ⟧ ⊢ ⟦Δ⟧` and `⟦Δ⟧ ⊢ ⟦Γ⟧`. -/
theorem structural_sound {left right : Bunch Loc Val}
    (relation : Structural left right) : SemanticallyEquivalent left right := by
  induction relation with
  | refl context => exact ⟨IProp.entails_refl _, IProp.entails_refl _⟩
  | symm relation induction => exact ⟨induction.2, induction.1⟩
  | trans first second firstIH secondIH =>
      exact ⟨IProp.entails_trans firstIH.1 secondIH.1,
        IProp.entails_trans secondIH.2 firstIH.2⟩
  | additiveCongr left right leftIH rightIH =>
      exact ⟨IProp.and_mono leftIH.1 rightIH.1, IProp.and_mono leftIH.2 rightIH.2⟩
  | multiplicativeCongr left right leftIH rightIH =>
      exact ⟨IProp.sep_mono leftIH.1 rightIH.1, IProp.sep_mono leftIH.2 rightIH.2⟩
  | additiveComm left right =>
      constructor <;> intro heap step holds <;> exact ⟨holds.2, holds.1⟩
  | additiveAssoc first second third =>
      constructor
      · intro heap step holds
        exact ⟨holds.1.1, holds.1.2, holds.2⟩
      · intro heap step holds
        exact ⟨⟨holds.1, holds.2.1⟩, holds.2.2⟩
  | additiveUnitLeft context =>
      constructor
      · exact IProp.and_elim_right IProp.truth context.denote
      · intro heap step holds
        exact ⟨True.intro, holds⟩
  | additiveUnitRight context =>
      constructor
      · exact IProp.and_elim_left context.denote IProp.truth
      · intro heap step holds
        exact ⟨holds, True.intro⟩
  | additiveContract context =>
      constructor
      · exact IProp.and_elim_left context.denote context.denote
      · intro heap step holds
        exact ⟨holds, holds⟩
  | multiplicativeComm left right =>
      exact ⟨IProp.sep_comm left.denote right.denote,
        IProp.sep_comm right.denote left.denote⟩
  | multiplicativeAssoc first second third =>
      exact ⟨IProp.sep_assoc_left first.denote second.denote third.denote,
        IProp.sep_assoc_right first.denote second.denote third.denote⟩
  | multiplicativeUnitLeft context =>
      exact ⟨IProp.sep_truth_left context.denote,
        IProp.sep_truth_intro_left context.denote⟩
  | multiplicativeUnitRight context =>
      exact ⟨IProp.sep_truth_right context.denote,
        IProp.sep_truth_intro_right context.denote⟩

/-- Affine deletion is sound: `Γ ⇝ Δ` implies `⟦Γ⟧ ⊢ ⟦Δ⟧`. -/
theorem weakening_sound {strong weak : Bunch Loc Val}
    (weakening : Weakening strong weak) : IProp.Entails strong.denote weak.denote := by
  induction weakening with
  | refl context => exact IProp.entails_refl _
  | discard context => exact IProp.truth_intro _
  | additive left right leftIH rightIH => exact IProp.and_mono leftIH rightIH
  | multiplicative left right leftIH rightIH => exact IProp.sep_mono leftIH rightIH

/-- A fully boxed context may be persisted:
`boxed Γ` implies `⟦Γ⟧ ⊢ □ ⟦Γ⟧`. -/
theorem boxed_sound {context : Bunch Loc Val} (boxed : Boxed context) :
    IProp.Entails context.denote (IProp.always context.denote) := by
  induction boxed with
  | empty => exact IProp.always_intro_from_truth (IProp.entails_refl IProp.truth)
  | hyp name proposition => exact IProp.always_idem_intro proposition
  | additive left right leftIH rightIH =>
      exact IProp.entails_trans (IProp.and_mono leftIH rightIH)
        (IProp.always_and_intro _ _)
  | multiplicative left right leftIH rightIH =>
      apply IProp.entails_trans
        (IProp.and_intro
          (IProp.entails_trans (IProp.sep_elim_left _ _) leftIH)
          (IProp.entails_trans (IProp.sep_elim_right _ _) rightIH))
      exact IProp.always_sep_intro _ _

theorem always_contraction (source leftName rightName : String)
    (proposition : IProp Loc Val) :
    SemanticallyEquivalent (.hyp source (IProp.always proposition))
      (.multiplicative (.hyp leftName (IProp.always proposition))
        (.hyp rightName (IProp.always proposition))) :=
  ⟨IProp.always_dup proposition,
    IProp.sep_elim_left (IProp.always proposition) (IProp.always proposition)⟩

theorem focus_fill {context : Bunch Loc Val} {name : String}
    {assertion : IProp Loc Val} {hole : Hole Loc Val} :
    focus name context = some (assertion, hole) ->
    context = hole.fill (.hyp name assertion) := by
  intro focused
  induction context generalizing assertion hole with
  | empty => simp [focus] at focused
  | hyp candidate proposition =>
      by_cases same : candidate = name
      · simp [focus, same] at focused
        obtain ⟨rfl, rfl⟩ := focused
        subst candidate
        rfl
      · simp [focus, same] at focused
  | additive left right leftIH rightIH =>
      cases leftFocused : focus name left with
      | some result =>
          obtain ⟨leftAssertion, leftHole⟩ := result
          have resultEqual :
              (leftAssertion, Hole.additiveLeft leftHole right) = (assertion, hole) := by
            simpa [focus, leftFocused] using focused
          cases resultEqual
          rw [leftIH leftFocused]
          rfl
      | none =>
          cases rightFocused : focus name right with
          | none => simp [focus, leftFocused, rightFocused] at focused
          | some result =>
              obtain ⟨rightAssertion, rightHole⟩ := result
              have resultEqual :
                  (rightAssertion, Hole.additiveRight left rightHole) = (assertion, hole) := by
                simpa [focus, leftFocused, rightFocused] using focused
              cases resultEqual
              rw [rightIH rightFocused]
              rfl
  | multiplicative left right leftIH rightIH =>
      cases leftFocused : focus name left with
      | some result =>
          obtain ⟨leftAssertion, leftHole⟩ := result
          have resultEqual :
              (leftAssertion, Hole.multiplicativeLeft leftHole right) = (assertion, hole) := by
            simpa [focus, leftFocused] using focused
          cases resultEqual
          rw [leftIH leftFocused]
          rfl
      | none =>
          cases rightFocused : focus name right with
          | none => simp [focus, leftFocused, rightFocused] at focused
          | some result =>
              obtain ⟨rightAssertion, rightHole⟩ := result
              have resultEqual :
                  (rightAssertion, Hole.multiplicativeRight left rightHole) =
                    (assertion, hole) := by
                simpa [focus, leftFocused, rightFocused] using focused
              cases resultEqual
              rw [rightIH rightFocused]
              rfl

namespace Hole

theorem or_lift (hole : Hole Loc Val) (source leftName rightName : String)
    (left right : IProp Loc Val) :
    IProp.Entails (hole.fill (.hyp source (IProp.or left right))).denote
      (IProp.or (hole.fill (.hyp leftName left)).denote
        (hole.fill (.hyp rightName right)).denote) := by
  induction hole with
  | here => exact IProp.entails_refl _
  | additiveLeft inside fixed induction =>
      intro heap step holds
      cases induction heap step holds.1 with
      | inl leftHolds => exact Or.inl ⟨leftHolds, holds.2⟩
      | inr rightHolds => exact Or.inr ⟨rightHolds, holds.2⟩
  | additiveRight fixed inside induction =>
      intro heap step holds
      cases induction heap step holds.2 with
      | inl leftHolds => exact Or.inl ⟨holds.1, leftHolds⟩
      | inr rightHolds => exact Or.inr ⟨holds.1, rightHolds⟩
  | multiplicativeLeft inside fixed induction =>
      intro heap step holds
      obtain ⟨leftHeap, rightHeap, disjoint, combined, insideHolds, fixedHolds⟩ := holds
      cases induction leftHeap step insideHolds with
      | inl leftHolds =>
          exact Or.inl ⟨leftHeap, rightHeap, disjoint, combined, leftHolds, fixedHolds⟩
      | inr rightHolds =>
          exact Or.inr ⟨leftHeap, rightHeap, disjoint, combined, rightHolds, fixedHolds⟩
  | multiplicativeRight fixed inside induction =>
      intro heap step holds
      obtain ⟨leftHeap, rightHeap, disjoint, combined, fixedHolds, insideHolds⟩ := holds
      cases induction rightHeap step insideHolds with
      | inl leftHolds =>
          exact Or.inl ⟨leftHeap, rightHeap, disjoint, combined, fixedHolds, leftHolds⟩
      | inr rightHolds =>
          exact Or.inr ⟨leftHeap, rightHeap, disjoint, combined, fixedHolds, rightHolds⟩

theorem exists_lift {Witness : Type w} (hole : Hole Loc Val)
    (source witnessName : String) (body : Witness -> IProp Loc Val) :
    IProp.Entails (hole.fill (.hyp source (IProp.exists_ body))).denote
      (IProp.exists_ fun witness =>
        (hole.fill (.hyp witnessName (body witness))).denote) := by
  induction hole with
  | here => exact IProp.entails_refl _
  | additiveLeft inside fixed induction =>
      intro heap step holds
      obtain ⟨witness, witnessHolds⟩ := induction heap step holds.1
      exact ⟨witness, witnessHolds, holds.2⟩
  | additiveRight fixed inside induction =>
      intro heap step holds
      obtain ⟨witness, witnessHolds⟩ := induction heap step holds.2
      exact ⟨witness, holds.1, witnessHolds⟩
  | multiplicativeLeft inside fixed induction =>
      intro heap step holds
      obtain ⟨leftHeap, rightHeap, disjoint, combined, insideHolds, fixedHolds⟩ := holds
      obtain ⟨witness, witnessHolds⟩ := induction leftHeap step insideHolds
      exact ⟨witness, leftHeap, rightHeap, disjoint, combined, witnessHolds, fixedHolds⟩
  | multiplicativeRight fixed inside induction =>
      intro heap step holds
      obtain ⟨leftHeap, rightHeap, disjoint, combined, fixedHolds, insideHolds⟩ := holds
      obtain ⟨witness, witnessHolds⟩ := induction rightHeap step insideHolds
      exact ⟨witness, leftHeap, rightHeap, disjoint, combined, fixedHolds, witnessHolds⟩

theorem later_lift (hole : Hole Loc Val) (source name : String)
    (proposition : IProp Loc Val) :
    IProp.Entails (hole.fill (.hyp source (IProp.later proposition))).denote
      (IProp.later (hole.fill (.hyp name proposition)).denote) := by
  induction hole with
  | here => exact IProp.entails_refl _
  | additiveLeft inside fixed induction =>
      exact IProp.entails_trans
        (IProp.and_mono induction (IProp.later_intro fixed.denote))
        (IProp.later_and_intro _ _)
  | additiveRight fixed inside induction =>
      exact IProp.entails_trans
        (IProp.and_mono (IProp.later_intro fixed.denote) induction)
        (IProp.later_and_intro _ _)
  | multiplicativeLeft inside fixed induction =>
      exact IProp.entails_trans
        (IProp.sep_mono induction (IProp.later_intro fixed.denote))
        (IProp.later_sep_intro _ _)
  | multiplicativeRight fixed inside induction =>
      exact IProp.entails_trans
        (IProp.sep_mono (IProp.later_intro fixed.denote) induction)
        (IProp.later_sep_intro _ _)

end Hole

theorem select_sound {name : String} {context selected remaining : Bunch Loc Val} :
    select name context = some (selected, remaining) ->
    IProp.Entails context.denote (IProp.sep selected.denote remaining.denote) := by
  intro selection
  unfold select at selection
  cases extracted : extract name context with
  | none => simp [extracted] at selection
  | some result =>
      obtain ⟨assertion, rest⟩ := result
      simp [extracted] at selection
      obtain ⟨rfl, rfl⟩ := selection
      exact extract_sound extracted

/-- A successful named partition reconstructs the original resources:
`partition hs Γ = (Γ₁, Γ₂)` implies `⟦Γ⟧ ⊢ ⟦Γ₁⟧ ∗ ⟦Γ₂⟧`. -/
theorem partition_sound {selectedNames : List String}
    {context selected remaining : Bunch Loc Val} :
    partition selectedNames context = some (selected, remaining) ->
    IProp.Entails context.denote (IProp.sep selected.denote remaining.denote) := by
  induction selectedNames generalizing context selected remaining with
  | nil => simp [partition]
  | cons name names induction =>
      cases names with
      | nil => simpa [partition] using
          (select_sound (name := name) (context := context)
            (selected := selected) (remaining := remaining))
      | cons next rest =>
          intro partitioned
          simp only [partition] at partitioned
          cases firstSelected : select name context with
          | none => simp [firstSelected] at partitioned
          | some firstResult =>
              obtain ⟨first, afterFirst⟩ := firstResult
              cases restSelected : partition (next :: rest) afterFirst with
              | none => simp [firstSelected, restSelected] at partitioned
              | some restResult =>
                  obtain ⟨selectedRest, finalContext⟩ := restResult
                  simp [firstSelected, restSelected] at partitioned
                  obtain ⟨rfl, rfl⟩ := partitioned
                  apply IProp.entails_trans (select_sound firstSelected)
                  apply IProp.entails_trans
                    (IProp.sep_mono (IProp.entails_refl first.denote)
                      (induction restSelected))
                  exact IProp.sep_assoc_right first.denote selectedRest.denote finalContext.denote

end Bunch

variable {Loc : Type u} {Val : Type v}

/-- Semantic validity of a proof-mode goal. -/
def Valid (context : Bunch Loc Val) (goal : IProp Loc Val) : Prop :=
  IProp.Entails context.denote goal

end MPSL.ProofMode
